language: ruby

services:
  - docker

before_install:
- docker build -t rafavilvert/sherlock:${TRAVIS_JOB_ID} .
- docker run rafavilvert/sherlock:${TRAVIS_JOB_ID} /bin/sh -c "yarn install --check-files"

script:
- docker run -it rafavilvert/sherlock:${TRAVIS_JOB_ID} rspec


deploy:
  provider: script
  script: bash echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push ${DOCKER_USERNAME}/sherlock:${TRAVIS_JOB_ID}
  git-hub-token: $GITHUB_TOKEN