language: ruby

services:
  - docker

before_install:
- docker build -t rafavilvert/sherlock:${TRAVIS_JOB_ID} .
- docker run rafavilvert/sherlock:${TRAVIS_JOB_ID} /bin/sh -c "yarn install --check-files"

script:
- docker run -it rafavilvert/sherlock:${TRAVIS_JOB_ID} rspec


after_success:
  - bash echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    docker push rafavilvert/sherlock:${TRAVIS_JOB_ID}